version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    image: fastapi-task-web:latest
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
    
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/task
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
